### PR TITLE
fix #107

### LINKED ISSUE #107: wait strategy conflict when two mysql databases are up (Port 33060 not bound after 60000ms)
I'm working on a monorepo using `nx`. I have two `docker-compose.yaml`s: one for my local dev environment which I have permanently up using `docker-compose up -d` and then one dedicated to e2e tests using `testcontainers`.

dev:
```yaml
version: "3"
services:
  db:
    container_name: leadgogo_dev_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASS}"
      - "MYSQL_DATABASE=${DB_DBNAME}"
    volumes:
      - ./leadgogo_20200624_1428AST.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
    ports:
      - "${DB_PORT}:3306"
```
e2e
```yaml
version: '3'
services:
  db:
    container_name: leadgogo_e2e_webapi_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASS}'
      - 'MYSQL_DATABASE=${DB_DBNAME}'
    volumes:
      - ./leadgogo_20200624_1428AST.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
    ports:
      - '${DB_PORT}:3306'
  migrations:
    container_name: leadgogo_e2e_webapi_migrations
    build: ./e2e-dist/sql-migrations
    environment:
      - 'DB_USER=${DB_USER}'
      - 'DB_PASS=${DB_PASS}'
      - DB_HOST=db
      - DB_PORT=3306
      - 'DB_DBNAME=${DB_DBNAME}'
    depends_on:
      - db
```

The e2e environment is activated in my jest test file like this:
```typescript
const environment = await new DockerComposeEnvironment(
  composeFilePath,
  composeFile
)
  .withBuild()
  .withWaitStrategy(
    'leadgogo_e2e_webapi_db',
    Wait.forLogMessage(`socket: '/var/run/mysqld/mysqld.sock'  port: 3306`)
  )
  .up();
```

When I have my dev docker compose up I can't run my e2e tests successfully. They always fail with the internal `testcontainers` error message `Port 33060 not bound after 60000ms`.

As soon as I deactivate the dev docker compose my e2e tests will consistently pass.

I have debug logs for both situations:
[with dev up](https://pastebin.com/FxarTi5P)
[with dev down](https://pastebin.com/G9iDSypF)

One obvious difference is in first one you see the debug message `testcontainers DEBUG Waiting for internal port 33060 +32ms` while in the second you do not.

### PR DESCRIPTION
**Pull request by rhyek**
In docker-compose up, filter started containers based on compose path and file. Fixes #107.

### CODE REVIEW

File: src/docker-compose-environment.ts [hunk 1]
```diff
@@ -109,7 +109,12 @@ export class DockerComposeEnvironment {
 
   private async findStartedContainers(dockerClient: DockerClient): Promise<Dockerode.ContainerInfo[]> {
     const containers = await dockerClient.listContainers();
-    return containers.filter((container) => container.Labels["com.docker.compose.version"] !== undefined);
+    return containers.filter(
+      (container) =>
+        container.Labels["com.docker.compose.version"] !== undefined &&
```
Comment (cristianrgreco) [inline src/docker-compose-environment.ts:114]: This is great, I hadn't noticed this. If we can filter by the workdir dir and config file we probably don't need com.docker.compose.version, I had added it just to get all containers started by docker-compose

Comment (rhyek) [reply src/docker-compose-environment.ts:114]: sorry, was going to do this as soon as I got home.
